### ISSUE TITLE
nutrition feature

### ISSUE THREAD

**Issue by mrVanDalo** [kmein/mahlzeit#1]
```yml
ingredient:
  - apple
    nutritions:
     kcal: 10000
     protein: 1000
     ...
```

always 100g per unit
(don't know about spoon)
